"""
shared/feature_extraction.py
-----------------------------
Compute the six HCDS features for a collection of result records.

Feature definitions (from paper Section 4 / Figure 1):

  f = [ℓ, H, s_H, C_para, ΔA_pert, ΔA_mech]

  1. ℓ   latency_per_token      t_gen / T_out
                                 Requires: generation wall-time logged during
                                 inference (stored in the result dict as
                                 'latency_per_token' or 'gen_time_s' +
                                 'num_tokens').
                                 PROXY if unavailable: output character count /
                                 1000  (relative ordering is preserved).

  2. H   mean_token_entropy      Mean of token-level entropy H_t = -Σ p log p.
                                 Requires: per-token logprobs stored as
                                 'token_entropies' (list) or 'entropy_mean'.
                                 PROXY: vocabulary type/token ratio of output.

  3. s_H entropy_slope           OLS slope of H_t over normalised position.
                                 Requires: same as entropy_mean.
                                 PROXY: 0.0 (flat) when logprobs unavailable.

  4. C   paraphrase_consistency  Fraction of paraphrase variants answered
                                 correctly (same answer as original).
                                 Requires: Task 3 records aligned to Task 1.

  5. ΔA_pert perturbation_sensitivity  A_orig − A_pert
                                 Requires: Task 2 records aligned to Task 1.

  6. ΔA_mech mechanistic_sensitivity   (A_base − A_anchor) − (A_base − A_control)
                                 = A_control − A_anchor
                                 Requires: intervention columns in result dict
                                 ('anchor_accuracy', 'control_accuracy').
                                 Returned as NaN when unavailable.

All features are computed per (question, model, mode) triple and returned
as a dict.  The caller is responsible for z-scoring across the full
(question × prompt) matrix before computing Euclidean distances.
"""

import math
import warnings
from typing import Dict, List, Optional

import numpy as np


# ── 1 & 2 & 3  Latency + Entropy (from stored inference metadata) ──────────

def _proxy_latency(output: str) -> float:
    """Character-count proxy for latency; used when real timing is absent."""
    return len(output) / 1000.0


def _proxy_entropy(output: str) -> float:
    """Unigram character-entropy proxy; used when logprobs are absent."""
    if not output:
        return 0.0
    from collections import Counter
    counts = Counter(output)
    total = len(output)
    return -sum((c / total) * math.log2(c / total + 1e-12) for c in counts.values())


def extract_linguistic_features(record: dict) -> Dict[str, float]:
    """Extract latency, entropy mean, and entropy slope from a result record.

    Priority order for each feature:
      - Use stored value if present (generated by generation.py with logging).
      - Fall back to proxy with a one-time warning.
    """
    # ── latency ──────────────────────────────────────────────────────────────
    if "latency_per_token" in record and record["latency_per_token"] is not None:
        latency = float(record["latency_per_token"])
    elif "gen_time_s" in record and "num_tokens" in record:
        latency = record["gen_time_s"] / max(record["num_tokens"], 1)
    else:
        warnings.warn(
            "latency_per_token not found in record — using character-count proxy. "
            "Re-run generation.py with timing enabled for accurate results.",
            RuntimeWarning,
            stacklevel=2,
        )
        latency = _proxy_latency(record.get("output", ""))

    # ── entropy ──────────────────────────────────────────────────────────────
    if "token_entropies" in record and record["token_entropies"]:
        entropies = np.asarray(record["token_entropies"], dtype=float)
        entropy_mean = float(np.mean(entropies))
        # OLS slope over normalised position [0, 1]
        n = len(entropies)
        if n >= 2:
            x = np.linspace(0, 1, n)
            x_c = x - x.mean()
            entropy_slope = float(np.dot(x_c, entropies - entropies.mean()) / np.dot(x_c, x_c))
        else:
            entropy_slope = 0.0
    elif "entropy_mean" in record and record["entropy_mean"] is not None:
        entropy_mean = float(record["entropy_mean"])
        entropy_slope = float(record.get("entropy_slope", 0.0))
    else:
        warnings.warn(
            "token_entropies not found in record — using vocabulary-diversity proxy. "
            "Re-run generation.py with logprob logging for accurate results.",
            RuntimeWarning,
            stacklevel=2,
        )
        entropy_mean = _proxy_entropy(record.get("output", ""))
        entropy_slope = 0.0

    return {
        "latency_per_token": latency,
        "entropy_mean": entropy_mean,
        "entropy_slope": entropy_slope,
    }


# ── 4  Paraphrase consistency ─────────────────────────────────────────────────

def compute_paraphrase_consistency(
    base_record: dict,
    paraphrase_records: List[dict],
) -> float:
    """Fraction of paraphrase variants that give the same correct/incorrect outcome.

    Args:
        base_record:        The original question result (correct: 0 or 1).
        paraphrase_records: List of result dicts for paraphrased versions of
                            the same question.  Expected field: 'correct'.

    Returns:
        Fraction in [0, 1].  If no paraphrase records, returns NaN.
    """
    if not paraphrase_records:
        return float("nan")
    base_correct = int(base_record.get("correct", 0))
    n_match = sum(
        1 for r in paraphrase_records
        if int(r.get("correct", 0)) == base_correct
    )
    return n_match / len(paraphrase_records)


# ── 5  Perturbation sensitivity ───────────────────────────────────────────────

def compute_perturbation_sensitivity(
    orig_record: dict,
    pert_records: List[dict],
) -> float:
    """ΔA_pert = A_orig − mean(A_pert).

    Args:
        orig_record:  Result dict for the unperturbed question.
        pert_records: List of result dicts for perturbed versions (renamed /
                      shuffled).  Expected field: 'correct'.

    Returns:
        Scalar in [-1, 1].  Positive means accuracy dropped under perturbation
        (consistent with reasoning dependence).  NaN if no pert_records.
    """
    if not pert_records:
        return float("nan")
    a_orig = float(orig_record.get("correct", 0))
    a_pert = float(np.mean([r.get("correct", 0) for r in pert_records]))
    return a_orig - a_pert


# ── 6  Mechanistic intervention sensitivity ───────────────────────────────────

def compute_mechanistic_sensitivity(record: dict) -> float:
    """ΔA_mech = A_control − A_anchor.

    The paper defines:
      ΔA_mech = (A_base − A_anchor) − (A_base − A_control)
              = A_control − A_anchor

    where A_base is the unintervened accuracy for this cell, A_anchor is the
    accuracy after zeroing the top-2 anchor steps, and A_control is the
    accuracy after zeroing matched random non-anchor steps.

    Expects fields 'anchor_accuracy' and 'control_accuracy' in the record.
    Returns NaN if these are missing (mechanistic sub-pipeline not yet run).
    """
    anchor  = record.get("anchor_accuracy")
    control = record.get("control_accuracy")
    if anchor is None or control is None:
        return float("nan")
    return float(control) - float(anchor)


# ── Master extractor ──────────────────────────────────────────────────────────

def extract_all_features(
    record: dict,
    paraphrase_records: Optional[List[dict]] = None,
    pert_records:       Optional[List[dict]] = None,
) -> Dict[str, float]:
    """Extract all six features for a single (question, mode) record.

    Args:
        record:             The primary result record.
        paraphrase_records: Paraphrase variants for feature 4 (optional).
        pert_records:       Perturbation variants for feature 5 (optional).

    Returns:
        Dict with keys: latency_per_token, entropy_mean, entropy_slope,
        paraphrase_consistency, perturbation_sensitivity, mechanistic_sensitivity.
        Missing features are NaN.
    """
    feats = extract_linguistic_features(record)

    feats["paraphrase_consistency"] = (
        compute_paraphrase_consistency(record, paraphrase_records)
        if paraphrase_records is not None
        else float("nan")
    )

    feats["perturbation_sensitivity"] = (
        compute_perturbation_sensitivity(record, pert_records)
        if pert_records is not None
        else float("nan")
    )

    feats["mechanistic_sensitivity"] = compute_mechanistic_sensitivity(record)

    return feats


FEATURE_NAMES = [
    "latency_per_token",
    "entropy_mean",
    "entropy_slope",
    "paraphrase_consistency",
    "perturbation_sensitivity",
    "mechanistic_sensitivity",
]
